sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run build
  - npm run test
after_success:
  - npm run semantic-release
